server:
  port: 9090


# 로컬 DB

#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: newyear
#    password: newyear
#    driver-class-name: oracle.jdbc.driver.OracleDriver

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springjpa
    password: springjpa
    driver-class-name: oracle.jdbc.driver.OracleDriver
    

# 원격 DB

#spring:
  #datasource:
    #url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=C:\\Wallet_lohp
    #url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=/Users/dohyeonpark/Wallet_lohp
    #url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=/Users/vanessa/importantKeyPair/Wallet_lohp
    #username: admin
    #password: HappyNewYear2023
    #driver-class-name: oracle.jdbc.driver.OracleDriver

#
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@lohp_high?TNS_ADMIN=./src/main/resources/oracleCloud/Wallet_lohp
#    username: admin
#    password: HappyNewYear2023
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    
    
  sens:
    NCP_SENS_ACCESS: QKlhgcIXEXKDhxNiay2d
    NCP_SENS_SECRET: anbHiCJCAIMZocnhOQN2yaPGvSUsewooTzCKD8rJ
    NCP_SENS_ID: ncp:sms:kr:297655669204:dhaparksns
    NCP_SENS_NUMBER: 01057371087
    
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      
      
logging.level:
  org.hibernate.SQL: debug 
  org.hibernate.type: trace
 